Pull Request
MaxMartinsen/JavaScript2_CA pull request #2
Opened 2023-09-25 11:12 UTC by MaxMartinsen

Profile updates do not currently work on the personal profile page, but all of them are displayed on the feed page. At the moment I am working on the transition by id as well as deletion and edit. Please give me your feedback.

2023-09-26 09:53 UTC, sulenchy requested changes
@MaxMartinsen You have 2065 files change? That is too much. You need to gitnore node_modules and dist folder.

2023-10-03 08:32 UTC, MaxMartinsen commented
Please look at my work and leave a review.
Now working on the profile page so that the feed of posts only from the profile is visible.
The post feed requires your attention, perhaps checking the URL of the text or image is not enough?
I'm not happy with the names of some of the functions; going to redesign them and make them more modular, I think this will help make the code more readable.

2023-10-03 09:34 UTC, MaxMartinsen commented
Remove node_modules from version control

2023-10-03 10:09 UTC, sulenchy commented on src/js/auth/login.js
> + * Login a user by making a POST request to the provided URL with the given user data.
This looks good to me

2023-10-03 10:12 UTC, sulenchy commented on src/js/auth/register.js
> +/**
This looks exactly like the login functionality. Why can't you just stick to one and remove the other? You can rename the loginUser function to a common name such as `fetch_auth`

2023-10-03 10:15 UTC, sulenchy commented on src/js/components/formatDateAndTime.js
> +export const formatDateAndTime = (dateString) => {
This file looks like a utility function and not a component. A component is more of UI than anything. Why don't you move it out to another folder such as `utils`.

2023-10-03 10:16 UTC, sulenchy commented on src/js/components/formatTag.js
> +export function formatTags(tags) {
Same thing as above

2023-10-03 10:16 UTC, sulenchy commented on src/js/components/setActiveFilter.js
> +export function setActiveFilter(filterId) {
Same as above

2023-10-03 10:30 UTC, sulenchy commented on src/js/display/displayPost.js
> +        const postImage = post.media ? `<img src="${post.media}" alt="Post Image" class="img-fluid rounded mb-3">` : '';
Good job! for having a placeholder for post image

2023-10-03 10:32 UTC, sulenchy commented on src/js/display/displayPost.js
> +        // Extract the post ID from the URL
I see that you are repeating in other places. Don’t you think having it as a util function would be better?

2023-10-31 14:31 UTC, MarvyK reviewed
@MaxMartinsen  - thanks for your submission of your PR. Good job on your submission. You can go ahead and merge into your main branch. Well done!

2023-11-02 06:48 UTC, merged